name: FastAPI tests and Docker deploy

on:
  pull_request:
    types: [opened, reopened, synchronize] # Run on PR open, reopen, or sync
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: set DATABASE_URL
        run: echo "DATABASE_URL=sqlite:///./test.db" > $GITHUB_ENV

      - name: Set up production database environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_USER=reconnect" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_NAME=reconnect" >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV

      - name: Run tests
        run: pytest tests

  build:
    runs-on: ubuntu-latest
    needs: test # Wait for the test job to complete

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Authenticate with GitHub using PAT
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
