name: FastAPI CI/CD to AWS

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  build:
    if: github.event.pull_request.merged == true # Only run on merged PRs
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Authenticate with GitHub using PAT
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

        # Deploy to AWS
